//! Error types

use {
    num_derive::FromPrimitive,
    solana_program::{
        decode_error::DecodeError,
        msg,
        program_error::{PrintProgramError, ProgramError},
    },
    thiserror::Error,
};

/// Errors that may be returned by the TokenSwap program.
#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum SwapError {
    // 0.
    /// The account cannot be initialized because it is already being used.
    #[error("Swap account already in use")]
    AlreadyInUse,
    /// The program address provided doesn't match the value generated by the
    /// program.
    #[error("Invalid program address generated from bump seed and key")]
    InvalidProgramAddress,
    /// The owner of the input isn't set to the program address generated by the
    /// program.
    #[error("Input account owner is not the program address")]
    InvalidOwner,
    /// The owner of the pool token output is set to the program address
    /// generated by the program.
    #[error("Output pool account owner cannot be the program address")]
    InvalidOutputOwner,
    /// The deserialization of the account returned something besides
    /// State::Mint.
    #[error("Deserialized account is not an SPL Token mint")]
    ExpectedMint,

    // 5.
    /// The deserialization of the account returned something besides
    /// State::Account.
    #[error("Deserialized account is not an SPL Token account")]
    ExpectedAccount,
    /// The input token account is empty.
    #[error("Input token account empty")]
    EmptySupply,
    /// The pool token mint has a non-zero supply.
    #[error("Pool token mint has a non-zero supply")]
    InvalidSupply,
    /// The provided token account has a delegate.
    #[error("Token account has a delegate")]
    InvalidDelegate,
    /// The input token is invalid for swap.
    #[error("InvalidInput")]
    InvalidInput,

    // 10.
    /// Address of the provided swap token account is incorrect.
    #[error("Address of the provided swap token account is incorrect")]
    IncorrectSwapAccount,
    /// Address of the provided pool token mint is incorrect
    #[error("Address of the provided pool token mint is incorrect")]
    IncorrectPoolMint,
    /// The output token is invalid for swap.
    #[error("InvalidOutput")]
    InvalidOutput,
    /// General calculation failure due to overflow or underflow
    #[error("General calculation failure due to overflow or underflow")]
    CalculationFailure,
    /// Invalid instruction number passed in.
    #[error("Invalid instruction")]
    InvalidInstruction,

    // 15.
    /// Swap input token accounts have the same mint
    #[error("Swap input token accounts have the same mint")]
    RepeatedMint,
    /// Swap instruction exceeds desired slippage limit
    #[error("Swap instruction exceeds desired slippage limit")]
    ExceededSlippage,
    /// The provided token account has a close authority.
    #[error("Token account has a close authority")]
    InvalidCloseAuthority,
    /// The pool token mint has a freeze authority.
    #[error("Pool token mint has a freeze authority")]
    InvalidFreezeAuthority,
    /// The pool fee token account is incorrect
    // retired: unreachable since SwapV2 — the fee-account slot this error
    // guarded is deleted; kept only because deleting a mid-enum
    // variant would renumber every discriminant after it.
    #[error("Pool fee token account incorrect")]
    IncorrectFeeAccount,

    // 20.
    /// Given pool token amount results in zero trading tokens
    #[error("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,
    /// The fee calculation failed due to overflow, underflow, or unexpected 0
    #[error("Fee calculation failed due to overflow, underflow, or unexpected 0")]
    FeeCalculationFailure,
    /// ConversionFailure
    #[error("Conversion to u64 failed with an overflow or underflow")]
    ConversionFailure,
    /// The provided fee does not match the program owner's constraints
    #[error("The provided fee does not match the program owner's constraints")]
    InvalidFee,
    /// The provided token program does not match the token program expected by
    /// the swap
    #[error("The provided token program does not match the token program expected by the swap")]
    IncorrectTokenProgramId,

    // 25.
    /// The provided curve type is not supported by the program owner
    #[error("The provided curve type is not supported by the program owner")]
    UnsupportedCurveType,
    /// The provided curve parameters are invalid
    #[error("The provided curve parameters are invalid")]
    InvalidCurve,
    /// The operation cannot be performed on the given curve
    #[error("The operation cannot be performed on the given curve")]
    UnsupportedCurveOperation,
    /// The pool fee account is invalid.
    // retired: unreachable since SwapV2 — same fate as IncorrectFeeAccount
    // above; kept for discriminant stability only.
    #[error("The pool fee account is invalid")]
    InvalidFeeAccount,
    /// Instruction has been retired; tag 0 (Initialize) was removed — use
    /// CreatePool.
    #[error("Instruction has been retired; tag 0 (Initialize) was removed — use CreatePool")]
    InstructionRetired,
    /// fee_bps does not match the fee parameters
    #[error("fee_bps does not match the fee parameters")]
    FeeBpsMismatch,
    /// The requested single-sided exact-out amount exceeds the LP-owned
    /// reserve on the withdrawn side (counter-owned protocol fees are
    /// excluded) — mirrors withdraw_all's X7/X9 clamp.
    #[error("Requested exact-out amount exceeds the LP-owned reserve")]
    ExceededLpReserve,

    // 32. The authority model (the design plan).
    /// `InitializeConfig` run against a config PDA that already belongs to
    /// this program (one-shot).
    #[error("Protocol config is already initialized")]
    ConfigAlreadyInitialized,
    /// The passed ProgramData account fails address/owner/shape verification.
    #[error("Invalid program data account")]
    InvalidProgramData,
    /// The program has no upgrade authority (ProgramData option flag = 0) —
    /// nothing can prove itself as the authority, so config can never be
    /// initialized for an immutable program.
    #[error("Program is immutable — no upgrade authority to verify")]
    ImmutableProgram,
    /// `InitializeConfig`'s signer does not match the upgrade authority
    /// parsed from ProgramData.
    #[error("Signer is not the program's upgrade authority")]
    InvalidConfigAuthority,

    // 36.
    /// An admin op (`SetTreasury` / `TransferAdmin` / `AcceptAdmin` /
    /// `SetPoolCreation`) or `CollectProtocolFees` ran against a config
    /// account that is absent or not version-1.
    #[error("Protocol config is not initialized")]
    ConfigNotInitialized,
    /// `CreatePool` ran with no live config — fail-closed: pool
    /// creation before genesis config is a program property, not a runbook
    /// promise.
    #[error("Pool creation is not configured yet")]
    PoolCreationNotConfigured,
    /// `CreatePool` with `pool_creation_mode == 0` (admin-only) and the payer
    /// is not `config.admin`.
    #[error("Pool creation is currently restricted to the admin")]
    PoolCreationRestricted,
    /// `SetTreasury` / `TransferAdmin` / `SetPoolCreation` signed by a key
    /// other than `config.admin`.
    #[error("Signer is not the protocol admin")]
    NotAdmin,

    // 40.
    /// `AcceptAdmin` signed by a key other than `config.pending_admin`
    /// (including when `pending_admin` is the default/none sentinel).
    #[error("Signer is not the pending admin")]
    NotPendingAdmin,
    /// `CollectProtocolFees`'s destination account fails one of: owner ==
    /// `config.treasury`, mint matches the pool's side, or key != the vault.
    #[error("Destination account is not a valid treasury destination")]
    InvalidTreasuryDestination,
    /// `InitializeConfig` / `SetTreasury` given the default (all-zero)
    /// pubkey for admin or treasury.
    #[error("Config value cannot be the default pubkey")]
    InvalidConfigValue,
    /// `InitializeConfig` / `SetPoolCreation` given a mode byte other than 0
    /// or 1.
    #[error("Pool creation mode must be 0 or 1")]
    InvalidPoolCreationMode,
}
impl From<SwapError> for ProgramError {
    fn from(e: SwapError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
impl<T> DecodeError<T> for SwapError {
    fn type_of() -> &'static str {
        "Swap Error"
    }
}

impl PrintProgramError for SwapError {
    fn print<E>(&self)
    where
        E: 'static
            + std::error::Error
            + DecodeError<E>
            + PrintProgramError
            + num_traits::FromPrimitive,
    {
        match self {
            SwapError::AlreadyInUse => msg!("Error: Swap account already in use"),
            SwapError::InvalidProgramAddress => {
                msg!("Error: Invalid program address generated from bump seed and key")
            }
            SwapError::InvalidOwner => {
                msg!("Error: The input account owner is not the program address")
            }
            SwapError::InvalidOutputOwner => {
                msg!("Error: Output pool account owner cannot be the program address")
            }
            SwapError::ExpectedMint => msg!("Error: Deserialized account is not an SPL Token mint"),
            SwapError::ExpectedAccount => {
                msg!("Error: Deserialized account is not an SPL Token account")
            }
            SwapError::EmptySupply => msg!("Error: Input token account empty"),
            SwapError::InvalidSupply => msg!("Error: Pool token mint has a non-zero supply"),
            SwapError::RepeatedMint => msg!("Error: Swap input token accounts have the same mint"),
            SwapError::InvalidDelegate => msg!("Error: Token account has a delegate"),
            SwapError::InvalidInput => msg!("Error: InvalidInput"),
            SwapError::IncorrectSwapAccount => {
                msg!("Error: Address of the provided swap token account is incorrect")
            }
            SwapError::IncorrectPoolMint => {
                msg!("Error: Address of the provided pool token mint is incorrect")
            }
            SwapError::InvalidOutput => msg!("Error: InvalidOutput"),
            SwapError::CalculationFailure => msg!("Error: CalculationFailure"),
            SwapError::InvalidInstruction => msg!("Error: InvalidInstruction"),
            SwapError::ExceededSlippage => {
                msg!("Error: Swap instruction exceeds desired slippage limit")
            }
            SwapError::InvalidCloseAuthority => msg!("Error: Token account has a close authority"),
            SwapError::InvalidFreezeAuthority => {
                msg!("Error: Pool token mint has a freeze authority")
            }
            SwapError::IncorrectFeeAccount => msg!("Error: Pool fee token account incorrect"),
            SwapError::ZeroTradingTokens => {
                msg!("Error: Given pool token amount results in zero trading tokens")
            }
            SwapError::FeeCalculationFailure => msg!(
                "Error: The fee calculation failed due to overflow, underflow, or unexpected 0"
            ),
            SwapError::ConversionFailure => msg!("Error: Conversion to or from u64 failed."),
            SwapError::InvalidFee => {
                msg!("Error: The provided fee does not match the program owner's constraints")
            }
            SwapError::IncorrectTokenProgramId => {
                msg!("Error: The provided token program does not match the token program expected by the swap")
            }
            SwapError::UnsupportedCurveType => {
                msg!("Error: The provided curve type is not supported by the program owner")
            }
            SwapError::InvalidCurve => {
                msg!("Error: The provided curve parameters are invalid")
            }
            SwapError::UnsupportedCurveOperation => {
                msg!("Error: The operation cannot be performed on the given curve")
            }
            SwapError::InvalidFeeAccount => {
                msg!("Error: The pool fee account is invalid")
            }
            SwapError::InstructionRetired => {
                msg!("Error: Instruction has been retired; tag 0 (Initialize) was removed — use CreatePool")
            }
            SwapError::FeeBpsMismatch => {
                msg!("Error: fee_bps does not match the fee parameters")
            }
            SwapError::ExceededLpReserve => {
                msg!("Error: Requested exact-out amount exceeds the LP-owned reserve")
            }
            SwapError::ConfigAlreadyInitialized => {
                msg!("Error: Protocol config is already initialized")
            }
            SwapError::InvalidProgramData => msg!("Error: Invalid program data account"),
            SwapError::ImmutableProgram => {
                msg!("Error: Program is immutable — no upgrade authority to verify")
            }
            SwapError::InvalidConfigAuthority => {
                msg!("Error: Signer is not the program's upgrade authority")
            }
            SwapError::ConfigNotInitialized => msg!("Error: Protocol config is not initialized"),
            SwapError::PoolCreationNotConfigured => {
                msg!("Error: Pool creation is not configured yet")
            }
            SwapError::PoolCreationRestricted => {
                msg!("Error: Pool creation is currently restricted to the admin")
            }
            SwapError::NotAdmin => msg!("Error: Signer is not the protocol admin"),
            SwapError::NotPendingAdmin => msg!("Error: Signer is not the pending admin"),
            SwapError::InvalidTreasuryDestination => {
                msg!("Error: Destination account is not a valid treasury destination")
            }
            SwapError::InvalidConfigValue => {
                msg!("Error: Config value cannot be the default pubkey")
            }
            SwapError::InvalidPoolCreationMode => {
                msg!("Error: Pool creation mode must be 0 or 1")
            }
        }
    }
}
