//! Tick ↔ sqrt-price conversion (Q64.64).
//!
//! `sqrt_price(tick) = sqrt(1.0001)^tick`, computed by bit-decomposition: for
//! each set bit `i` of `|tick|`, multiply the accumulator by the precomputed
//! `SQRT_RATIOS[i] = sqrt(1.0001)^(2^i)` (Q64.64); invert for negative ticks.
//!
//! The `SQRT_RATIOS` constants were generated by EXACT BigInt fixed-point
//! (repeated squaring of `isqrt(1.0001·2^128)`) and cross-checked against an
//! INDEPENDENT path (compute `1.0001^tick` then integer-sqrt) — the two agree to
//! ~2.5e-10 relative across a full-range sweep. Tests below re-assert both the
//! exact reference vectors and the independent-path tolerance, plus monotonicity
//! and the `sqrt(t)·sqrt(-t) ≈ 2^128` symmetry.

use {super::Q64, crate::error::ClmmError, spl_math::uint::U256};

/// Minimum usable tick (price ≈ 1.0001^-443636).
pub const MIN_TICK: i32 = -443636;
/// Maximum usable tick.
pub const MAX_TICK: i32 = 443636;
/// `sqrt_price` at [`MIN_TICK`] (Q64.64), inclusive lower bound.
pub const MIN_SQRT_PRICE: u128 = 4295048016;
/// `sqrt_price` at [`MAX_TICK`] (Q64.64), inclusive upper bound.
pub const MAX_SQRT_PRICE: u128 = 79226673515399013880257568879;

/// `SQRT_RATIOS[i] = round(sqrt(1.0001)^(2^i) · 2^64)`, i = 0..=19.
const SQRT_RATIOS: [u128; 20] = [
    18447666387855959850,
    18448588748116922569,
    18450433606991734259,
    18454123878217468671,
    18461506635090006683,
    18476281010653910107,
    18505865242158249966,
    18565175891880433370,
    18684368066214940275,
    18925053041275764047,
    19415764168677885645,
    20435687552633174797,
    22639080592224297029,
    27784196929998385068,
    41848122137994941923,
    94936283578220170147,
    488590176327620415397,
    12941056668319120408908,
    9078618265828695359366874,
    4468068147272989105925714484762,
];

#[inline]
fn mul_shift(acc: u128, ratio: u128) -> Result<u128, ClmmError> {
    let p = (U256::from(acc) * U256::from(ratio)) >> 64;
    u128::try_from(p).map_err(|_| ClmmError::MathOverflow)
}

/// `sqrt_price` (Q64.64) at `tick`. `Err(TickOutOfBounds)` outside the range.
pub fn get_sqrt_price_at_tick(tick: i32) -> Result<u128, ClmmError> {
    if !(MIN_TICK..=MAX_TICK).contains(&tick) {
        return Err(ClmmError::TickOutOfBounds);
    }
    let abs = tick.unsigned_abs();
    let mut r: u128 = Q64;
    let mut bit = 0u32;
    while bit < 20 {
        if (abs >> bit) & 1 == 1 {
            r = mul_shift(r, SQRT_RATIOS[bit as usize])?;
        }
        bit += 1;
    }
    if tick < 0 {
        // invert: 2^128 / r  (full-width, no u128 overflow of 2^128).
        let inv = (U256::from(1u8) << 128) / U256::from(r);
        r = u128::try_from(inv).map_err(|_| ClmmError::MathOverflow)?;
    }
    Ok(r)
}

/// Largest `tick` with `get_sqrt_price_at_tick(tick) <= sqrt_price`.
///
/// Binary search over the forward map (monotone) — ~20 iterations, correct and
/// simple. Used off the swap hot path (init / range validation); the pool tracks
/// `current_tick` in state, so a swap never recomputes this per step.
pub fn get_tick_at_sqrt_price(sqrt_price: u128) -> Result<i32, ClmmError> {
    if !(MIN_SQRT_PRICE..=MAX_SQRT_PRICE).contains(&sqrt_price) {
        return Err(ClmmError::SqrtPriceOutOfBounds);
    }
    let (mut lo, mut hi) = (MIN_TICK, MAX_TICK);
    while lo < hi {
        // upper-mid so the search converges to the largest satisfying tick.
        let mid = lo + (hi - lo + 1) / 2;
        if get_sqrt_price_at_tick(mid)? <= sqrt_price {
            lo = mid;
        } else {
            hi = mid - 1;
        }
    }
    Ok(lo)
}

#[cfg(test)]
mod tests {
    use super::*;

    // (tick, expected sqrt_price) — EXACT, from the ratios-path generator.
    const VEC: &[(i32, u128)] = &[
        (0, 18446744073709551616),
        (1, 18447666387855959850),
        (-1, 18445821805675392312),
        (10, 18455969290605290415),
        (-10, 18437523468038800970),
        (100, 18539204128674405694),
        (-100, 18354745142194483680),
        (1000, 19392480388906835027),
        (-1000, 17547129613991599912),
        (10000, 30412779051191529115),
        (-10000, 11188795550323333171),
        (100000, 2737055259406564611100),
        (-100000, 124324258982888375),
        (443636, 79226673515399013880257568879),
        (-443636, 4295048016),
    ];

    #[test]
    fn exact_reference_vectors() {
        for &(t, want) in VEC {
            assert_eq!(get_sqrt_price_at_tick(t).unwrap(), want, "tick {t}");
        }
    }

    #[test]
    fn tick_zero_is_one() {
        assert_eq!(get_sqrt_price_at_tick(0).unwrap(), Q64);
    }

    // GENUINELY independent oracle: f64 float math (`sqrt(1.0001^tick)·2^64`) is a
    // different code path from the integer bit-decomposition, so agreement is
    // NOT circular. The tolerance (1e-7 relative) sits far above f64's ~1e-10
    // accumulation over |tick| up to 443636, yet far below the ≥1e-6 error a
    // WRONG magic constant would produce — this is the real guard against a
    // constant regression. (The prior VEC_INDEP was a second *integer* path that
    // shared the code's floor-error and asserted a vacuous ppb bound; replaced.)
    #[test]
    fn matches_float_oracle() {
        for t in (MIN_TICK..=MAX_TICK).step_by(521) {
            let got = get_sqrt_price_at_tick(t).unwrap() as f64;
            let want = (1.0001_f64).powi(t).sqrt() * 2f64.powi(64);
            let rel = (got - want).abs() / want;
            assert!(rel < 1e-7, "tick {t}: got {got:.3e} vs oracle {want:.3e} rel {rel:.2e}");
        }
    }

    #[test]
    fn bounds_and_out_of_range() {
        assert_eq!(get_sqrt_price_at_tick(MIN_TICK).unwrap(), MIN_SQRT_PRICE);
        assert_eq!(get_sqrt_price_at_tick(MAX_TICK).unwrap(), MAX_SQRT_PRICE);
        assert_eq!(get_sqrt_price_at_tick(MIN_TICK - 1), Err(ClmmError::TickOutOfBounds));
        assert_eq!(get_sqrt_price_at_tick(MAX_TICK + 1), Err(ClmmError::TickOutOfBounds));
    }

    #[test]
    fn monotonic_increasing() {
        let mut prev = 0u128;
        let mut t = MIN_TICK;
        while t <= MAX_TICK {
            let v = get_sqrt_price_at_tick(t).unwrap();
            assert!(v > prev, "not monotonic at {t}");
            prev = v;
            t += 97;
        }
    }

    #[test]
    fn symmetry_product_is_two_pow_128() {
        // sqrt(t) * sqrt(-t) ≈ 2^128 (price·1/price). Within rounding tolerance.
        for &t in &[1, 10, 100, 1000, 50000, 400000] {
            let a = get_sqrt_price_at_tick(t).unwrap();
            let b = get_sqrt_price_at_tick(-t).unwrap();
            let prod = U256::from(a) * U256::from(b);
            let target = U256::from(1u8) << 128;
            let diff = if prod > target { prod - target } else { target - prod };
            // relative tolerance ~1e-9 of 2^128
            let tol = target / U256::from(1_000_000_000u64);
            assert!(diff <= tol, "symmetry off at tick {t}");
        }
    }

    #[test]
    fn tick_at_sqrt_price_round_trips() {
        for &t in &[MIN_TICK, -100000, -1000, -1, 0, 1, 1000, 100000, MAX_TICK - 1] {
            let sp = get_sqrt_price_at_tick(t).unwrap();
            let back = get_tick_at_sqrt_price(sp).unwrap();
            // back is the largest tick with sqrt<=sp, so it must equal t.
            assert_eq!(back, t, "round-trip tick {t}");
            // and one above must exceed sp.
            if t < MAX_TICK {
                assert!(get_sqrt_price_at_tick(t + 1).unwrap() > sp);
            }
        }
    }
}
